# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import issues.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='文章名稱', max_length=64)),
                ('content', models.TextField(blank=True, help_text='文章內容')),
                ('image', models.ImageField(blank=True, help_text='文章影像', max_length=128, upload_to=issues.utils.article_image_url)),
                ('url', models.URLField(blank=True, help_text='文章連結網址', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='專欄名稱', max_length=32)),
                ('description', models.TextField(blank=True, help_text='專欄說明文字')),
                ('remarks', models.CharField(help_text='專欄用途註記，不會顯示在實際電子報上', max_length=16)),
                ('layout', models.CharField(help_text='專欄版型', max_length=32)),
                ('position', models.IntegerField(default=0, help_text='專欄排序順序')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(help_text='發行日期')),
                ('term', models.IntegerField(default=issues.utils.current_term, editable=False, help_text='發行屆數')),
                ('editable', models.BooleanField(default=True, editable=False, help_text='可否編輯')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='templates.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='提供者名稱', max_length=32)),
                ('description', models.TextField(blank=True, help_text='提供者說明文字')),
                ('icon', models.ImageField(help_text='提供者 Logo', upload_to=issues.utils.provider_image_url)),
                ('site_url', models.URLField(blank=True, help_text='提供者網站網址', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issues.Column'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
        migrations.AddField(
            model_name='article',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.Provider'),
        ),
    ]
