# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='範本預覽縮圖', max_length=256),
        ),
        migrations.AlterField(
            model_name='template',
            name='path',
            field=models.FilePathField(help_text='範本檔案位置', match='\\.mustache$', max_length=128, path='/Source/student-weekly/themes', recursive=True),
        ),
    ]
