# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_add_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='templates.Template'),
        ),
    ]
